### ISSUE TITLE
The plugin sometimes tries to remove null from whitelist

### ISSUE THREAD

**Issue by MarijnIsN00B** [hyperdefined/AutoWhitelistRemove#1]
The title says it all basically, it sometimes tries to remove null from the whitelist, here is the line:
[AutoWhitelistRemove] Removing player null from the whitelist! They haven't played in over 3 weeks! Last online: 2706 weeks ago.
Player is not whitelisted

**Comment by hyperdefined** [comment]
The `null` is what the player's username would of be, seems either it's not loading the username or data from the whitelist. 

Is your server offline or online? Do you mind sharing `whitelist.json` so I can try to reproduce the issue?

**Comment by hyperdefined** [comment]
This issue should be fixed in the latest version. Let me know if the issue still continues.

https://github.com/hyperdefined/AutoWhitelistRemove/releases/tag/1.1
